### ISSUE TITLE
Corrections nécessaire sur la page d'un jeu de données

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#338]
**section Contacts**
- [x] `mailto` ne fonctionne pas (#347)

**section Informations technique**
- [x] Faute "Autre informations" (#345)
- [x] La date de mise à jour n'est pas la bonne. Il s'agit pour le moment de la date du dernier moissonnage. (#347)
- [x] Ajouter l'échelle de la donnée (#347)
- [x] Ajouter la résolution de la donnée (#347)

**section Étendue spatiale**
- [x] Bloquer les contrôles (#347)
